fastlane_version "2.54.4"

default_platform :ios

platform :ios do

  #
  # Learn more here: https://docs.fastlane.tools/getting-started/ios/beta-deployment/
  #             and: https://docs.fastlane.tools/getting-started/android/beta-deployment/
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'swishlist', export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : ['lawtjh@gmail.com', 'guy@swish.gifts', 'laura@swish.gifts'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: 'cac53e8af4ffea564a6d329088d2a0f4c33c4303',
             build_secret: '323f17beacda7ba38337b9973ab75383ae7cfdb4410f3733008214d2c607244d',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    slack(
      slack_url: "https://hooks.slack.com/services/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",
      channel: "swishlist_development",
      message: "App successfully released!",
    )

    increment_build_number(build_number: values[:build_number])

  end


 #  lane :appstore do
 #  	snapshot
 #  	match(type: "appstore")
 #  	gym(scheme: "swishlist",
 #      workspace: "swishlist.xcworkspace",
 #      include_bitcode: false)
 #  	appstore
 #  	slack(message: "Successfully uploaded a new App Store build")
	# end  

end
