# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :CI do
	  run_tests(project: "TruthOrDare.xcodeproj",
      devices: ["iPhone 6s"],
      scheme: "TruthOrDare")
  end

  lane :CD do |values|

    gym(scheme: 'TruthOrDare', project: "TruthOrDare.xcodeproj", clean: true, silent: true, include_bitcode: false, export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : ['lawtjh@gmail.com'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: 'ccecd894afb473edc8152a03eea12a134cb9e970',
             build_secret: '4094f91a9ae4c861e895e9a7864c533e471ca4a85ec8ba6ea45082a6bc16422e',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    end
end
