# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :release do
    cert(
      development: true,
      username: "pmuthuraju@ztech.io"
    )
    match(app_identifier: "com.pridfastlane.test.app1", username: "pmuthuraju@ztech.io")
    build_app(scheme: "test")
  end
  #lane :CI do
  #	  run_tests(project: "TruthOrDare.xcodeproj",
  #    devices: ["iPhone 6s"],
  #    scheme: "TruthOrDare")
  #end

  #lane :CD do |values|

  #  gym(scheme: 'TruthOrDare', project: "TruthOrDare.xcodeproj", clean: true, silent: true, include_bitcode: false, export_method: 'ad-hoc')

  #  emails = values[:test_email] ? values[:test_email] : ['lawtjh@gmail.com'] # You can list more emails here
  #  groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here
  #end
end

